### ISSUE TITLE
new exercise: figs directory

### ISSUE THREAD

**Issue by maglet** [carpentries-incubator/swc-ext-python#17]
if we change the script to be in the directory above the directory and use the code in the current lesson to write out the file, the figures end up in the data folder. Have an exercise to have them do more string splitting to get the plots into a new folder called figs

Answer:
# save the plot with a unique file name
    split_name1 = file.split('.')[0] #data/gapminder_gdp_XXX
    split_name2 = file.split('/')[1]
    save_name = 'figs/'+split_name2 + '.png'
    plt.savefig(save_name)

**Comment by maglet** [comment]
I ended up putting this directly into the lesson. but i might move it.

**Comment by sstevens2** [comment]
This looks good.  The names don't match quite right but I'll make a PR to fix that and ask for your review.
